Adds Router Guards
revaturelabs/client-engagement-portal-front pull request #86
Opened 2020-11-23 20:03 UTC by Alteras1

2020-11-23 21:01 UTC, Hernandezn commented
Nathan & Colin are working on a version of this that persists after the user leaves the page.

2020-11-24 19:27 UTC, ar-pearse requested changes
Fix merge conflicts

2020-11-24 20:50 UTC, ar-pearse approved these changes

2020-11-24 21:07 UTC, Alteras1 commented
Using Nathan and Colin's version instead.
Better fit for the specs of the application since there's really only 2 main pages. endpoint-guard was made with multiple pages in mind instead.

2020-11-24 21:07 UTC, closed without merging